<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tetrad-configuration [
        <!ELEMENT tetrad-configuration (session-node*)>
        <!ELEMENT session-node (models, display-component, model-chooser, tooltip)>
        <!ELEMENT models (model+)>
        <!ELEMENT model (logger?, model-class, editor-class, params-class?, params-editor-class?)>
        <!ELEMENT params-editor-class (#PCDATA)>
        <!ELEMENT params-class (#PCDATA)>
        <!ELEMENT logger (event+)>
        <!ELEMENT event EMPTY>
        <!ELEMENT model-class (#PCDATA)>
        <!ELEMENT editor-class (#PCDATA)>
        <!ELEMENT display-component (#PCDATA)>
        <!ELEMENT model-chooser (#PCDATA)>
        <!ELEMENT tooltip (#PCDATA)>

        <!ATTLIST event id NMTOKENS #REQUIRED description CDATA #REQUIRED default (on|off) #IMPLIED>
        <!ATTLIST display-component image NMTOKENS #IMPLIED>
        <!ATTLIST model-chooser title NMTOKENS #REQUIRED>
        <!ATTLIST session-node id ID #REQUIRED>
        <!ATTLIST model name NMTOKENS #REQUIRED acronym NMTOKENS #REQUIRED help NMTOKENS #REQUIRED category NMTOKENS #IMPLIED>
        ]>
<tetrad-configuration>
    <session-node id="Graph">
        <models>
            <model name="Directed Acyclic Graph" acronym="DAG" help="dag">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DagWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.DagEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.GraphParams</params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.GraphParamsEditor
                </params-editor-class>
            </model>
            <model name="Structural Equation Model Graph" acronym="SEM Graph"
                   help="sem_graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemGraphEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.GraphParams</params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.GraphParamsEditor
                </params-editor-class>
            </model>
            <model name="General Graph" acronym="Graph" help="general_graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GraphWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.GraphParams</params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.GraphParamsEditor
                </params-editor-class>
            </model>
        </models>
        <display-component image="graphIcon.gif"/>
        <model-chooser title="Graph Types"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) No inputs OR
                 <br> (2) Data (to extract variables)
                 <br><i> Also (to extract a graph) any of these:
                 <br>Search, PM, IM, Estimator, Updator</i>
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="GraphManip">
        <models>
            <model name="Choose Dag in Pattern" acronym="Dag in Pattern"
                   help="graph">
                <model-class>edu.cmu.tetradapp.model.ChooseDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor</editor-class>
            </model>
            <model name="Generate Pattern from Dag" acronym="Pattern from Dag"
                   help="graph">
                <model-class>edu.cmu.tetradapp.model.PatternFromDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make Bidirected Edges Undirected" acronym="Pattern from Dag"
                   help="graph">
                <model-class>edu.cmu.tetradapp.model.BidirectedToUndirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Extract Markov Blanket" acronym="MB from Graph"
                   help="graph">
                <model-class>edu.cmu.tetradapp.model.ExtractMarkovBlanketWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
        </models>
        <display-component image="graphIcon.gif"/>
        <model-chooser title="Graph Manipulations"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) Search OR
                 <br> (2) Graph
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="PM">
        <models>
            <model name="Bayes Parametric Model" acronym="Bayes PM"
                   help="bayes_pm">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesPmWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesPmEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesPmParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesPmParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM Parametric Model" acronym="SEM PM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemPmWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemPmEditor
                </editor-class>
            </model>
            <!--<model name="SEM2 Parametric Model" acronym="SEM2 PM" help="sem2_pm">-->
                <!--<logger>-->
                    <!--<event id="info" description="Information" default="on"/>-->
                    <!--<event id="pm" description="Parametric Model"/>-->
                <!--</logger>-->
                <!--<model-class>edu.cmu.tetradapp.model.Sem2PmWrapper</model-class>-->
                <!--<editor-class>edu.cmu.tetradapp.editor.Sem2PmEditor-->
                <!--</editor-class>-->
            <!--</model>-->
            <!--<model name="Boolean Glass Gene PM" acronym="Glass PM"-->
                   <!--help="glass_pm">-->
                <!--<model-class>edu.cmu.tetradapp.model.BooleanGlassGenePm-->
                <!--</model-class>-->
                <!--<editor-class>-->
                    <!--edu.cmu.tetradapp.gene.editor.BooleanGlassGenePmEditor-->
                <!--</editor-class>-->
            <!--</model>-->
        </models>
        <display-component image="pmIcon.gif"/>
        <model-chooser title="Types of Parameterized Models"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) Graph, OR
                 <br> (2) Graph AND Data (to extract discrete categories)
                 <br><i> Also (to extract a PM) any of these:
                 <br>IM, Estimator</i>
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="IM">
        <models>
            <model name="Bayes Instantiated Model" acronym="Bayes IM"
                   help="bayes_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesImWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="Dirichlet Bayes Instantiated Model"
                   acronym="Dir Bayes IM" help="dirichlet_bayes_im">
                <model-class>edu.cmu.tetradapp.model.DirichletBayesImWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DirichletBayesImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.DirichletBayesImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.DirichletBayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM Instantiated Model" acronym="SEM IM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.SemImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SemImParamsEditor
                </params-editor-class>
            </model>
            <!--<model name="SEM2 Instantiated Model" acronym="SEM2 IM" help="sem2_im">-->
                <!--<logger>-->
                    <!--<event id="info" description="Information" default="on"/>-->
                    <!--<event id="pm" description="Parametric Model"/>-->
                <!--</logger>-->
                <!--<model-class>edu.cmu.tetradapp.model.Sem2ImWrapper</model-class>-->
                <!--<editor-class>edu.cmu.tetradapp.editor.Sem2ImEditor-->
                <!--</editor-class>-->
            <!--</model>-->
            <!--<model name="Boolean Glass Gene IM" acronym="Glass IM"-->
                   <!--heldp="glass_im">-->
                <!--<model-class>edu.cmu.tetradapp.model.BooleanGlassGeneIm-->
                <!--</model-class>-->
                <!--<editor-class>-->
                    <!--edu.cmu.tetradapp.gene.editor.BooleanGlassGeneImEditor-->
                <!--</editor-class>-->
            <!--</model>-->
        </models>
        <display-component image="imIcon.gif"/>
        <model-chooser title="Types of Instantiated Models"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) PM (Bayes or SEM), OR
                 <br> (2) IM (to convert Dirichlet Bayes IM to Bayes IM), OR
                 <br> (3) Estimator (to extract IM)
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="Data">
        <models>
            <model name="Data Wrapper" acronym="Data" help="data">
                <model-class>edu.cmu.tetradapp.model.DataWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Bayes IM Simulated Data" acronym="Bayes Data"
                   help="data">
                <model-class>edu.cmu.tetradapp.model.BayesDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesDataParamsEditor
                </params-editor-class>
            </model>
            <model name="Dirichlet Bayes IM Simulated Data"
                   acronym="Dir Bayes Data" help="data">
                <model-class>edu.cmu.tetradapp.model.DirichletBayesDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesDataParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM IM Simulated Data" acronym="SEM Data" help="data">
                <model-class>edu.cmu.tetradapp.model.SemDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.SemDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SemDataParamsEditor
                </params-editor-class>
            </model>
            <!--<model name="SEM2 IM Simulated Data" acronym="SEM2 Data" help="data">-->
                <!--<model-class>edu.cmu.tetradapp.model.Sem2DataWrapper-->
                <!--</model-class>-->
                <!--<editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>-->
                <!--<params-class>edu.cmu.tetradapp.model.Sem2DataParams-->
                <!--</params-class>-->
                <!--<params-editor-class>-->
                    <!--edu.cmu.tetradapp.editor.Sem2DataParamsEditor-->
                <!--</params-editor-class>-->
            <!--</model>-->
        </models>
        <display-component image="dataIcon.gif"/>
        <model-chooser title="Types of data Objects"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) No inputs (standalone data set), OR
                 <br> (2) IM (Bayes or SEM, to simulate data)
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="DataManip">
        <models>
            <model name="Discretize Dataset" acronym="Discretize" help="data"
                   category="General">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.DiscretizationWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>
                    edu.cmu.tetradapp.model.datamanip.DiscretizationParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.DiscretizationParamsEditor
                </params-editor-class>
            </model>
            <model name="Convert Numerical Discrete To Continuous" acronym="ConvertDiscrete" help="convertdiscrete"
                   category="General">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.ConvertNumericalDiscreteToContinuousWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Expand Case Multipliers" acronym="Expand" help="data"
                   category="General">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.ExpandCaseMultipliersWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Calculate" acronym="Calculate" help="data"
                   category="General">
                <model-class>
                    edu.cmu.tetradapp.model.calculator.CalculatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>
                    edu.cmu.tetradapp.model.calculator.CalculatorParams
                </params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.CalculatorEditor
                </params-editor-class>
            </model>
            <model name="Convert to Correlation Matrix" acronym="Corr Matrix"
                   help="data" category="Convert">
                <model-class>edu.cmu.tetradapp.model.CorrMatrixConverter
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
             <model name="Convert to Covariance Matrix" acronym="Cov Matrix"
                   help="data" category="Convert">
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <!--<model name="Invert covariance matrix" acronym="InvertCov"-->
                   <!--help="data" category="Convert">-->
                <!--<model-class>edu.cmu.tetradapp.model.datamanip.InvertCovMatrixWrapper-->
                <!--</model-class>-->
                <!--<editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>-->
            <!--</model>-->
            <model name="Convert to Time Series" acronym="Time Series"
                   help="data" category="Convert">
                <model-class>edu.cmu.tetradapp.model.datamanip.TimeSeriesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.datamanip.TimeSeriesParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.TimeSeriesParamsEditor
                </params-editor-class>
            </model>
            <model name="Convert to AR residuals" acronym="AR Residuals"
                   help="data" category="Convert">
                <model-class>edu.cmu.tetradapp.model.datamanip.ArResidualsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.datamanip.ArResidualsParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.ArResidualsParamsEditor
                </params-editor-class>
            </model>
            <model name="Remove Cases with Missing Values"
                   acronym="Remove Values" help="data"
                   category="Missing Values">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.RemoveMissingValueCasesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Replace Missing Values with Column Mode"
                   acronym="Replace Missing" help="data"
                   category="Missing Values">
                <model-class>edu.cmu.tetradapp.model.ModeInterpolatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Replace Missing Values with Column Mean"
                   acronym="Replace Missing" help="data"
                   category="Missing Values">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.MeanInterpolatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Replace Missing Values with Regression Predictions"
                   acronym="Replace Missing" help="data"
                   category="Missing Values">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.RegressionInterpolatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Replace Missing Values by Extra Category"
                   acronym="Replace Missing" help="data"
                   category="Missing Values">
                <model-class>
                    edu.cmu.tetradapp.model.ExtraCategoryInterpolatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Inject Missing Data Randomly" acronym="Inject Missing"
                   help="data" category="Missing Values">
                <model-class>edu.cmu.tetradapp.model.MissingDataInjectorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.MissingDataInjectorParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.MissingDataInjectorParamsEditor
                </params-editor-class>
            </model>
            <model name="Convert to Standardized Form" acronym="Standardized"
                   help="data" category="Convert">
                <model-class>edu.cmu.tetradapp.model.DataStandardizer
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Construct Boostrap Sample"
                   acronym="Bootstrap" help="data" category="Row operations">
                <logger>
                    <event id="sampleSize" description="Sample Size"
                           default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BootstrapSamplerWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.BootstrapSamplerParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BootstrapSamplerParamsEditor
                </params-editor-class>
            </model>
            <model name="Split By Cases" acronym="Split Cases" help="split"
                   category="Row operations">
                <model-class>edu.cmu.tetradapp.model.datamanip.SplitCasesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.datamanip.SplitCasesParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SplitCasesParamsEditor
                </params-editor-class>
            </model>
            <model name="Permute Rows" acronym="Permute Rows" help="permuterows"
                   category="Row operations">
                <model-class>edu.cmu.tetradapp.model.datamanip.PermuteRowsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Copy Continuous Variables" acronym="Copy Continuous"
                   help="data" category="Column operations">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.SubsetContinuousVariablesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Copy Discrete Variables" acronym="Copy Discrete"
                   help="data" category="Column operations">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.SubsetDiscreteVariablesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Copy Selected Variables" acronym="Copy Selected"
                   help="data" category="Column operations">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.SubsetSelectedVariablesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Remove Constant Columns" acronym="Remove Values"
                   help="data" category="Column operations">
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.RemoveConstantColumnsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Restrict to Graph Nodes" acronym="Restrict"
                   help="restrict" category="Column operations">
                <model-class>edu.cmu.tetradapp.model.RestrictToGraphNodes
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
        </models>
        <display-component image="dataIcon.gif"/>
        <model-chooser title="Types of Data Manipulations">
            edu.cmu.tetradapp.app.CategorizingModelChooser
        </model-chooser>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Notes:
                 <br> (1) Data, OR
                 <br> (2) Data Manipulation Node
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="Estimator">
        <models>
            <model name="ML Bayes Estimator" acronym="ML Bayes Est"
                   help="bayes_estimator">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesEstimatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesEstimatorEditor
                </editor-class>
            </model>
            <model name="SEM Estimator" acronym="SEM Est" help="sem_estimator">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="estimate" description="Estimate" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemEstimatorWrapper
                </model-class>
                <!--<editor-class>edu.cmu.tetradapp.editor.SemImEditor-->
                <editor-class>edu.cmu.tetradapp.editor.SemEstimatorEditor
                </editor-class>
            </model>
            <model name="Dirichlet Estimator" acronym="Dir Bayes Est"
                   help="dirichlet_estimator">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Intantiated Model"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DirichletEstimatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DirichletBayesImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.DirichletEstimatorParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.DirichletEstimatorParamsEditor
                </params-editor-class>
            </model>
            <!--<model name="EM Bayes Estimator" acronym="Em Bayes Est" help="em_bayes_estimator">-->
            <!--<logger>-->
            <!--<event id="info" description="Information" default="on"/>-->
            <!--<event id="estimate" description="Estimate"/>-->
            <!--</logger>-->
            <!--<model-class>edu.cmu.tetradapp.model.EmBayesEstimatorWrapper</model-class>-->
            <!--<editor-class>edu.cmu.tetradapp.editor.EmBayesEstimatorEditor</editor-class>-->
            <!--<params-class>edu.cmu.tetradapp.model.EmBayesEstimatorParams</params-class>-->
            <!--<params-editor-class>edu.cmu.tetradapp.editor.EMBayesEstimatorParamsEditor</params-editor-class>-->
            <!--</model>-->
            <!--<model name="Structural EM" acronym="Struct EM" help="struct_em">-->
            <!--<model-class>edu.cmu.tetradapp.model.StructEmBayesSearchRunner</model-class>-->
            <!--<editor-class>edu.cmu.tetradapp.editor.StructEmBayesSearchEditor</editor-class>-->
            <!--<params-class>edu.cmu.tetradapp.model.StructEmBayesSearchParams</params-class>-->
            <!--<params-editor-class>edu.cmu.tetradapp.editor.StructEMBayesSearchParamsEditor</params-editor-class>-->
            <!--</model>-->
        </models>
        <display-component image="estimatorIcon.gif"/>
        <model-chooser title="Types of Estimators"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Combinations:
                 <br> (1) PM and Data, OR
                 <br> (2) IM and Data (shortcut for IM->PM + Data)
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="Updater">
        <models>
            <model name="Approximate Updater" acronym="Aproox Up"